from . import mdm_position
from . import mdm_village
from . import custom_res_partner
from . import mdm_breed
from . import mdm_species
from . import mdm_type_public
from . import mdm_resource
from . import mdm_culture
from . import mdm_type_agriculture
from . import mdm_type_industry
from . import mdm_type_labor
from . import mdm_type_livestock
from . import mdm_type_service
from . import mdm_economy
from . import mdm_society
from . import mdm_welfare_benefit
from . import mdm_type_plumbing
from . import mdm_type_electricity
from . import mdm_type_street
from . import mdm_position_group